'''

Project Euler Problem 2:

Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

'''

def main():
    sum_ = 0

    i, j = 1, 1

    while i < 4000000:
        i, j = i + j, i

        if i % 2 == 0:
            sum_ += i

    print(sum_)


if __name__ == '__main__':
    main()
